2017-12-14 11:28:54,924 -- DEBUG -- __main__ -- main.py[line:15]  -- hello debug
2017-12-14 16:52:45,387 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 GET / (::1) 1.50ms
2017-12-14 16:52:47,964 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 GET /favicon.ico (::1) 0.50ms
2017-12-14 16:54:14,618 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 16:54:20,437 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 16:55:22,994 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/sdf/sdf (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/sdf/sdf', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '65e76f5b-c8cd-4185-bd33-83e76c35ebcf', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 20, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'
2017-12-14 16:55:23,006 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 20, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 16:55:23,008 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/sdf/sdf (192.168.1.6) 15.04ms
2017-12-14 16:56:29,052 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/service_user/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/service_user/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '63f2694a-529e-4da5-8981-63195dd99646', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 20, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'
2017-12-14 16:56:32,773 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 20, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 16:56:32,780 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/service_user/Reg (192.168.1.6) 3728.73ms
2017-12-14 16:57:10,737 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 16:59:17,910 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/service_user/Reg (192.168.1.6) 1.00ms
2017-12-14 17:00:13,786 -- INFO -- tornado.access -- web.py[line:2063]  -- 304 GET / (::1) 0.50ms
2017-12-14 17:00:20,499 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 GET /favicon.ico (::1) 0.50ms
2017-12-14 17:00:25,450 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/service_user/Reg (192.168.1.6) 0.44ms
2017-12-14 17:01:03,487 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 17:01:27,724 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/service_user/Reg (192.168.1.6) 0.50ms
2017-12-14 17:02:11,990 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 17:02:17,743 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/service_user/Reg (192.168.1.6) 1.00ms
2017-12-14 17:03:00,534 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 4889.28ms
2017-12-14 17:03:13,321 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 17:03:20,571 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 1.50ms
2017-12-14 17:04:05,020 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 17:05:03,589 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'd66bb6a9-e40d-42c1-a5e6-f5ceb68f9d67', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 22, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'
2017-12-14 17:05:03,592 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 22, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:05:03,594 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 7.01ms
2017-12-14 17:05:36,997 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 17:05:45,069 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 1.50ms
2017-12-14 17:43:23,901 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler\handler_base.py modified; restarting server
2017-12-14 17:45:00,017 -- INFO -- tornado.access -- web.py[line:2063]  -- 304 GET / (::1) 2.01ms
2017-12-14 17:45:00,100 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 GET /favicon.ico (::1) 0.50ms
2017-12-14 17:45:03,772 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'd9a945e1-7254-49ad-aed3-3099a1a26f5b', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'
2017-12-14 17:45:03,774 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 9, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:45:03,775 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 4.51ms
2017-12-14 17:45:38,350 -- INFO -- tornado.general -- autoreload.py[line:198]  -- main.py modified; restarting server
2017-12-14 17:45:40,645 -- INFO -- tornado.general -- autoreload.py[line:198]  -- main.py modified; restarting server
2017-12-14 17:45:51,242 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'dda84227-40b6-4873-bbe7-1f42841e9260', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'
2017-12-14 17:45:51,243 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    amod = __import__("service.", class_name.lower(), fromlist=True)
ModuleNotFoundError: No module named 'service.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 9, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:45:51,245 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 7.02ms
2017-12-14 17:46:23,957 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:46:31,919 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 115.81ms
2017-12-14 17:46:43,161 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:47:20,340 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 112.80ms
2017-12-14 17:47:38,603 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:47:44,402 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:47:47,359 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 116.34ms
2017-12-14 17:48:08,704 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 17:48:13,011 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'e4dbb559-8794-4b70-ba2b-08ed5b5cceb6', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 24, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 6, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 17:48:13,015 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 24, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 6, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 9, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:48:13,017 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 116.81ms
2017-12-14 17:48:38,534 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 17:48:44,489 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'adbea307-7948-4d13-9645-9d90ec95807d', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 24, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 17:48:44,492 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 24, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 9, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:48:44,494 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 119.32ms
2017-12-14 17:49:53,940 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:50:10,194 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'ee4d63bc-7560-4e85-bc98-b7e1d0ea917f', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    json.loads(param)
NameError: name 'json' is not defined
2017-12-14 17:50:10,196 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    json.loads(param)
NameError: name 'json' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 9, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:50:10,199 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 117.31ms
2017-12-14 17:50:45,321 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'bc8412b1-9a93-475f-a0d6-d7f380f73850', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    json.loads(param)
NameError: name 'json' is not defined
2017-12-14 17:50:45,322 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 21, in post
    json.loads(param)
NameError: name 'json' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 9, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:50:45,323 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 2.51ms
2017-12-14 17:51:07,140 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:51:15,083 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '4fd2bd41-c699-48bf-8c9e-f5eb16754c04', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '18', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 17:51:15,085 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:51:15,086 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 121.32ms
2017-12-14 17:51:45,805 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '460395ee-88f1-4308-80f5-86095efd7e59', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 17:51:45,811 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:51:45,814 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 8049.94ms
2017-12-14 17:51:50,407 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'c1cd7bff-5286-46f3-a93e-0a410cc502ed', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 17:51:50,408 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:51:50,410 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 4.01ms
2017-12-14 17:52:10,963 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 17:52:15,898 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '448131dc-2e71-4014-b7dd-e17ed5a26055', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers
2017-12-14 17:52:15,900 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:52:15,902 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 116.31ms
2017-12-14 17:54:52,726 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:55:00,122 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'eb3d2152-3144-4c59-be9a-537c29ef5897', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers
2017-12-14 17:55:00,124 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:55:00,127 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 115.30ms
2017-12-14 17:55:29,732 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:55:36,821 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'd6eedcb8-c5c1-4dc3-a776-1e57d4fbf57e', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers
2017-12-14 17:55:36,823 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:55:36,824 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 112.82ms
2017-12-14 17:56:03,457 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:56:13,781 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 110.29ms
2017-12-14 17:56:19,821 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:56:31,248 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '3ac977c7-8fb5-498f-be8c-df8263730231', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers
2017-12-14 17:56:31,250 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 8, in Reg
    print(param["token"])
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 17:56:31,251 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 115.31ms
2017-12-14 17:56:51,474 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 17:56:55,038 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 111.30ms
2017-12-14 17:58:14,297 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 18:00:17,102 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '85b80808-4cf7-455e-bd99-93dd7a311e87', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 27, in post
    rt1 = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 9, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 18:00:17,104 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 27, in post
    rt1 = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 9, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 18:00:17,105 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 111.80ms
2017-12-14 18:00:59,957 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:01:01,781 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:01:07,608 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 109.29ms
2017-12-14 18:01:16,597 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:01:18,975 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '5d441723-7891-4c8d-b114-d81551f34771', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt1 = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 9, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 18:01:18,978 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt1 = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 9, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 18:01:18,979 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 116.81ms
2017-12-14 18:01:44,435 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:01:50,595 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': '17984842-a459-4cf9-8f3a-58ff90f987a5', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt1 = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 9, in Reg
    return param["token"]
TypeError: string indices must be integers
2017-12-14 18:01:50,598 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt1 = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 9, in Reg
    return param["token"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 18:01:50,599 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 116.81ms
2017-12-14 18:03:46,520 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:03:54,861 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:04:06,201 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:04:19,413 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 113.30ms
2017-12-14 18:04:29,512 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:04:32,765 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 111.80ms
2017-12-14 18:06:16,333 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 18:06:19,639 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:06:23,288 -- ERROR -- tornado.application -- web.py[line:1590]  -- Uncaught exception POST /api/usermng/Reg (192.168.1.6)
HTTPServerRequest(protocol='http', host='192.168.1.6:8888', method='POST', uri='/api/usermng/Reg', version='HTTP/1.1', remote_ip='192.168.1.6', headers={'Cache-Control': 'no-cache', 'Postman-Token': 'cb97e532-075d-44ca-ab0a-40356c95c220', 'Content-Type': 'application/json', 'User-Agent': 'PostmanRuntime/6.4.1', 'Accept': '*/*', 'Host': '192.168.1.6:8888', 'Accept-Encoding': 'gzip, deflate', 'Content-Length': '19', 'Connection': 'keep-alive'})
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 14, in Reg
    return json.dump(rt)
TypeError: dump() missing 1 required positional argument: 'fp'
2017-12-14 18:06:23,290 -- ERROR -- tornado.application -- web.py[line:1038]  -- Uncaught exception in write_error
Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1509, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 26, in post
    rt = ret(param)
  File "D:\cc-space\code\cshop\api\service\usermng.py", line 14, in Reg
    return json.dump(rt)
TypeError: dump() missing 1 required positional argument: 'fp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ProgramFiles\Python36\lib\site-packages\tornado\web.py", line 1036, in send_error
    self.write_error(status_code, **kwargs)
  File "D:\cc-space\code\cshop\api\handler_base.py", line 10, in write_error
    logger.error(**kwargs)
TypeError: error() missing 1 required positional argument: 'msg'
2017-12-14 18:06:23,291 -- ERROR -- tornado.access -- web.py[line:2063]  -- 500 POST /api/usermng/Reg (192.168.1.6) 112.80ms
2017-12-14 18:09:37,952 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 18:09:55,229 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 107.82ms
2017-12-14 18:12:11,130 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:12:12,953 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\handler_base.py modified; restarting server
2017-12-14 18:12:16,738 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 107.78ms
2017-12-14 18:18:04,810 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 18:18:08,791 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/Reg (192.168.1.6) 109.85ms
2017-12-14 18:18:14,787 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/reg (192.168.1.6) 0.50ms
2017-12-14 18:22:38,127 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
2017-12-14 18:27:58,129 -- INFO -- tornado.access -- web.py[line:2063]  -- 200 POST /api/usermng/reg (192.168.1.6) 110.80ms
2017-12-14 18:28:18,430 -- INFO -- tornado.general -- autoreload.py[line:198]  -- D:\cc-space\code\cshop\api\service\usermng.py modified; restarting server
